steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']

  # Run tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
    env:
      - 'CI=true'

  # Build the Next.js application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'app'
      - 'deploy'
      - '--quiet'
      - '--promote'
      - '--stop-previous-version'

# Build timeout
timeout: '1200s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 